import 'package:audioplayers/audioplayers.dart';

/// Handles all game audio: a looping BGM, looping engine/siren beds, and a
/// small pool of one-shot SFX players. All sources are original synthesized
/// WAV assets generated by tool/gen_audio.dart.
class AudioManager {
  bool enabled = true;
  bool _started = false;

  final List<AudioPlayer> _sfxPool = [];
  int _sfxIdx = 0;

  final AudioPlayer _bgm = AudioPlayer();
  final AudioPlayer _engine = AudioPlayer();
  final AudioPlayer _siren = AudioPlayer();
  bool _engineOn = false;
  bool _sirenOn = false;

  Future<void> init() async {
    for (int i = 0; i < 6; i++) {
      final p = AudioPlayer();
      await p.setReleaseMode(ReleaseMode.stop);
      await p.setPlayerMode(PlayerMode.lowLatency);
      _sfxPool.add(p);
    }
    await _bgm.setReleaseMode(ReleaseMode.loop);
    await _engine.setReleaseMode(ReleaseMode.loop);
    await _siren.setReleaseMode(ReleaseMode.loop);
  }

  /// Browsers block audio until a user gesture; call this from key/pointer
  /// handlers so the BGM can start.
  Future<void> ensureStarted() async {
    if (_started || !enabled) return;
    _started = true;
    try {
      await _bgm.play(AssetSource('audio/bgm.wav'), volume: 0.3);
    } catch (_) {}
  }

  void sfx(String name, {double volume = 1.0}) {
    if (!enabled || !_started) return;
    final p = _sfxPool[_sfxIdx];
    _sfxIdx = (_sfxIdx + 1) % _sfxPool.length;
    p.play(AssetSource('audio/$name.wav'), volume: volume.clamp(0.0, 1.0));
  }

  void setEngine(bool on, double speedFactor) {
    if (!enabled) {
      if (_engineOn) { _engine.stop(); _engineOn = false; }
      return;
    }
    if (on && !_engineOn) {
      _engineOn = true;
      _engine.play(AssetSource('audio/engine.wav'), volume: 0.0);
    } else if (!on && _engineOn) {
      _engineOn = false;
      _engine.stop();
    }
    if (_engineOn) {
      _engine.setVolume((0.18 + speedFactor * 0.5).clamp(0.0, 0.7));
    }
  }

  void setSiren(bool on) {
    if (!enabled) {
      if (_sirenOn) { _siren.stop(); _sirenOn = false; }
      return;
    }
    if (on && !_sirenOn) {
      _sirenOn = true;
      _siren.play(AssetSource('audio/siren.wav'), volume: 0.28);
    } else if (!on && _sirenOn) {
      _sirenOn = false;
      _siren.stop();
    }
  }

  Future<void> toggle() async {
    enabled = !enabled;
    if (!enabled) {
      await _bgm.stop();
      await _engine.stop();
      await _siren.stop();
      _engineOn = false;
      _sirenOn = false;
      _started = false;
    } else {
      await ensureStarted();
    }
  }
}
